### ISSUE TITLE
Any reasons to avoid using Guzzle?

### ISSUE THREAD

**Issue by ndobromirov** [trilbymedia/grav-plugin-slack-invite#2]

**Comment by w00fz** [comment]
Just no use for it. We are using the `php-slack` library `frlnc/php-slack` which wraps Slack's API and makes the use of Guzzle unnecessary.

Why you ask?

**Comment by ndobromirov** [comment]
I was doing a PHP sack integration to make channel invites library. I was researching already available implementations and stumbled upon this repository and was curious of how you did the communication with Slak.

Aparently I've missed `frlnc/php-slack` library in my research :) :+1:
